test(engine): improve awaitility usage
Improve the alias for the awaitility and uses the supplier and consumer
feature to print out when it fails what was the last supplied position
etc.

Looks like this:

org.awaitility.core.ConditionTimeoutException: Condition with alias 'Await the TIMER.CREATED to be processed at position 9223372036854775807' didn't complete within 1 seconds because assertion condition defined as a lambda expression in io.camunda.zeebe.engine.util.EngineRule [Last process position should be greater or equal to 9223372036854775807]
Expecting:
  5L
to be greater than or equal to:
  9223372036854775807L