fix: add missing grpc dependency declarations
Found by the dependency analyzer after updating grpc-bom to 1.58.0
```
dependency:3.6.0:analyze-only (analyze-dependencies) @ zeebe-client-java
Error:  Used undeclared dependencies found:
Error:     io.grpc:grpc-util:jar:1.58.0:runtime
Error:     io.grpc:grpc-inprocess:jar:1.58.0:test

dependency:3.6.0:analyze-only (analyze-dependencies) @ zeebe-gateway
Error:  Used undeclared dependencies found:
Error:     io.grpc:grpc-inprocess:jar:1.58.0:test
```