test: allow lazy containers to be reused
previously if the container was closed and used again we would end up
with:

java.lang.IllegalStateException: Mapped port can only be obtained after the container is started

this probably can happen if we have a failed test and then attempt to
re-run the test

(cherry picked from commit 99412be5af8c2d6e9223df98f623274568fcda2a)